In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.2)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install pyodbc

Requirement already satisfied: pyodbc in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [7]:
df = pd.read_csv(
    r"C:\Users\anurag\Desktop\Sales_ETL_Project\Data\Superstore.csv",
    encoding='latin1'
)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
print(df.shape)

(9994, 21)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [10]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

In [12]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
print(df.shape)

(9994, 21)

In [15]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 1.6 MB

In [17]:
df['Order_Year'] = df['Order Date'].dt.year

In [18]:
df['Order_Month'] = df['Order Date'].dt.month

In [19]:
df['Profit_Margin'] = (
    df['Profit'] / df['Sales']
) * 100

In [35]:
df[['Sales','Profit','Profit_Margin']].head()

      Sales    Profit  Profit_Margin
0  261.9600   41.9136          16.00
1  731.9400  219.5820          30.00
2   14.6200    6.8714          47.00
3  957.5775 -383.0310         -40.00
4   22.3680    2.5164          11.25

In [36]:
print("Total Sales:", round(df['Sales'].sum(),2))

Total Sales: 2297200.86

In [37]:
print("Total Profit:", round(df['Profit'].sum(),2))

Total Profit: 286397.02

In [38]:
print("Total Orders:", df['Order ID'].nunique())

Total Orders: 5009

In [45]:
df.to_csv(
    r"C:\Users\anurag\Desktop\Sales_ETL_Project\Output\Cleaned_Superstore.csv",
    index=False
)
print("File Saved Successfully")

File Saved Successfully

In [46]:
from sqlalchemy import create_engine

In [47]:
engine = create_engine(
    "postgresql+psycopg2://postgres:Anurag123@localhost:5432/sales_etl"
)

In [48]:
conn = engine.connect()

print("Connected Successfully")

Connected Successfully

In [49]:
df.to_sql(
    "sales_data",
    engine,
    if_exists="replace",
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully